const cities = [
{name : "San Francisco", id: 1},
{name : "Hamburg", id: 2},
{name : "New Delhi", id: 3},
{name : "Bristol", id: 4},
{name : "Manchester", id: 5},
{name : "Edinburgh", id: 6},
{name : "Philadelphia", id: 7},
{name : "Madrid", id: 8},
{name : "Leeds", id: 9},
{name : "Berlin", id: 10},
{name : "Buenos Aires", id: 11},
{name : "Barcelona", id: 12},
{name : "Hong Kong", id: 13},
{name : "Honolulu", id: 14},
{name : "Long Beach", id: 15},
{name : "Amsterdam", id: 16},
{name : "Dongguan", id: 17},
{name : "Munich", id: 18},
{name : "Albuquerque", id: 19},
{name : "Santiago", id: 20},
{name : "Milwaukee", id: 21},
{name : "Riyadh", id: 22},
{name : "Oxford", id: 23},
{name : "Brussels", id: 24},
{name : "Cambridge", id: 25},
{name : "Dallas", id: 26},
{name : "Dhaka", id: 27},
{name : "Sheffield", id: 28},
{name : "Phoenix", id: 29},
{name : "Glasgow", id: 30},
{name : "Damascus", id: 31},
{name : "Auckland", id: 32},
{name : "Charlotte", id: 33},
{name : "Bogotá", id: 34},
{name : "Toronto", id: 35},
{name : "Cologne", id: 36},
{name : "Shenzhen", id: 37},
{name : "Tianjin", id: 38},
{name : "San Antonio", id: 39},
{name : "Kolkata", id: 40},
{name : "Cairo", id: 41},
{name : "Athens", id: 42},
{name : "Denver", id: 43},
{name : "London", id: 44},
{name : "Guangzhou", id: 45},
{name : "Paris", id: 46},
{name : "Austin", id: 47},
{name : "Mexico City", id: 48},
{name : "Omaha", id: 49},
{name : "Perth", id: 50},
{name : "Seoul", id: 51},
{name : "Wichita", id: 52},
{name : "Birmingham", id: 53},
{name : "Ankara", id: 54},
{name : "Tucson", id: 55},
{name : "Colorado Springs", id: 56},
{name : "Boston", id: 57},
{name : "Kinshasa", id: 58},
{name : "Rio de Janeiro", id: 59},
{name : "New York", id: 60},
{name : "Las Vegas", id: 61},
{name : "São Paulo", id: 62},
{name : "New Orleans", id: 63},
{name : "Istanbul", id: 64},
{name : "Karachi", id: 65},
{name : "Kansas City", id: 66},
{name : "Bangkok", id: 67},
{name : "Tokyo", id: 68},
{name : "Miami", id: 69},
{name : "Louisville", id: 70},
{name : "San Jose", id: 71},
{name : "Birmingham", id: 72},
{name : "Atlanta", id: 73},
{name : "Dublin", id: 74},
{name : "Lima", id: 75},
{name : "Osaka", id: 76},
{name : "Rome", id: 77},
{name : "Boise", id: 78},
{name : "Santa Cruz", id: 79},
{name : "Houston", id: 80},
{name : "Sydney", id: 81},
{name : "Washington DC", id: 82},
{name : "Milan", id: 83},
{name : "Richmond", id: 84},
{name : "Dubai", id: 85},
{name : "Chicago", id: 86},
{name : "Ho Chi Minh City", id: 87},
{name : "Jacksonville", id: 88},
{name : "Virginia Beach", id: 89},
{name : "Little Rock", id: 90},
{name : "Mumbai", id: 91},
{name : "Wilmington", id: 92},
{name : "Pyongyang", id: 93},
{name : "Tehrān", id: 94},
{name : "Baltimore", id: 95},
{name : "Beijing", id: 96},
{name : "Budapest", id: 97},
{name : "Indianapolis", id: 98},
{name : "Santorini", id: 99},
{name : "Seattle", id: 100},
{name : "Lagos", id: 101},
{name : "Bucharest", id: 102},
{name : "San Diego", id: 103},
{name : "Sacramento", id: 104},
{name : "Liverpool", id: 105},
{name : "Los Angeles", id: 106},
{name : "Mesa", id: 107},
{name : "Torino", id: 108},
{name : "Shanghai", id: 109},
{name : "Fresno", id: 110},
{name : "Brisbane", id: 111},
{name : "Columbus", id: 112},
{name : "Montréal", id: 113},
{name : "Addis Ababa", id: 114},
{name : "Melbourne", id: 115},
{name : "Prague", id: 116},
{name : "Exeter", id: 117},
{name : "Detroit", id: 118},
{name : "Bradford", id: 119},
{name : "Yokohama", id: 120},
{name : "Singapore", id: 121},
{name : "Casablanca", id: 122},
{name : "Oklahoma City", id: 123},
{name : "Toulouse", id: 124},
{name : "Bangalore", id: 125},
{name : "Moscow", id: 126},
{name : "Vancouver", id: 127},
{name : "Baghdad", id: 128},
{name : "Nairobi", id: 129},
{name : "Vienna", id: 130},
{name : "Fort Worth", id: 131},
{name : "Bridgeport", id: 132},
{name : "Anchorage", id: 133},
{name : "Nashville", id: 134},
{name : "Warsaw", id: 135},
{name : "Memphis", id: 136},
{name : "Jakarta", id: 137},
{name : "Hyderabad", id: 138},
{name : "Belfast", id: 139},
{name : "Copenhagen", id: 140},
{name : "Zagreb", id: 141},
{name : "Portland", id: 142},
{name : "Stockholm", id: 143},
{name : "Wakefield", id: 144},
{name : "Calgary", id: 145},
{name : "Nice", id: 146},
{name : "Adelaide", id: 147},
{name : "Naples", id: 148},
{name : "Cardiff", id: 149},
{name : "Fargo", id: 150},
{name : "Wuhan", id: 151},
{name : "Kiev", id: 152},
{name : "Cheyenne", id: 153},
{name : "Oslo", id: 154},
{name : "Lille", id: 155},
{name : "Marseille", id: 156},
{name : "Manila", id: 157},
{name : "Bordeaux", id: 158},
{name : "Ahmedabad", id: 159},
{name : "Sendai", id: 160},
{name : "Lahore", id: 161},
{name : "Edmonton", id: 162},
{name : "Lyon", id: 163},
{name : "Maracaibo", id: 164},
{name : "Johannesburg", id: 165},
{name : "Caracas", id: 166},
{name : "Bremen", id: 167},
{name : "Stoke-on-Trent", id: 168},
{name : "St Petersburg", id: 169},
{name : "İzmir", id: 170},
{name : "Charleston", id: 171},
{name : "Santander", id: 172},
{name : "Raleigh", id: 173},
{name : "Sofia", id: 174},
{name : "El Paso", id: 175},
{name : "Brasília", id: 176},
{name : "Salvador", id: 177},
];

export default cities;